name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Run tests
      run: ./gradlew test --no-daemon --console=plain
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: build/reports/tests/test/
        retention-days: 7
    
    - name: Upload test logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-logs
        path: build/test-results/test/
        retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Build plugin
      run: ./gradlew buildPlugin --no-daemon
    
    - name: Verify plugin
      run: ./gradlew verifyPlugin --no-daemon
    
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin-artifact
        path: build/distributions/*.zip
        retention-days: 7

  # Optional: Run plugin verifier to check compatibility
  verify-compatibility:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        ide-version:
          - '2023.2'
          - '2023.3'
          - '2024.1'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Run Plugin Verifier
      run: ./gradlew runPluginVerifier -Pplugin.verifier.ide.versions=${{ matrix.ide-version }} --no-daemon
      continue-on-error: true
