name: Compatibility Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  test-matrix:
    name: Test on ${{ matrix.os }} with IDE ${{ matrix.ide-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        ide-version: ['2023.2', '2023.3', '2024.1']
        java-version: ['17']
        include:
          # Test with Java 21 on latest IDE version
          - os: ubuntu-latest
            ide-version: '2024.1'
            java-version: '21'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      if: runner.os != 'Windows'
      run: chmod +x gradlew
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Run tests
      run: ./gradlew test --no-daemon --console=plain
    
    - name: Build plugin
      run: ./gradlew buildPlugin -x buildSearchableOptions --no-daemon
    
    - name: Verify plugin for IDE ${{ matrix.ide-version }}
      run: ./gradlew verifyPlugin -Pplugin.verifier.ide.versions=${{ matrix.ide-version }} --no-daemon
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.ide-version }}-java${{ matrix.java-version }}
        path: build/reports/tests/test/
        retention-days: 7
    
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      if: success() && matrix.os == 'ubuntu-latest' && matrix.java-version == '17'
      with:
        name: plugin-${{ matrix.ide-version }}
        path: build/distributions/*.zip
        retention-days: 7

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: test-matrix
    if: always()
    
    steps:
    - name: Check test results
      run: |
        if [ "${{ needs.test-matrix.result }}" == "success" ]; then
          echo " All compatibility tests passed!"
        else
          echo " Some compatibility tests failed."
          exit 1
        fi
